<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_60.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



In [2]:
transactions = np.array([
      5000, -2000, 15000, -4500, 7000,
      -12000, 25000, -3000, 8000, -18000,
      4500, 22000, -6000, 9000, -2500
])

In [3]:
# Extract deposits.
deposits = transactions[transactions > 0]
deposits

array([ 5000, 15000,  7000, 25000,  8000,  4500, 22000,  9000])

In [4]:
# Extract withdrawals.
withdrawals = transactions[transactions < 0]
withdrawals

array([ -2000,  -4500, -12000,  -3000, -18000,  -6000,  -2500])

In [5]:
# Calculate total deposits and withdrawals.
total_d = np.sum(deposits)
total_w = np.sum(withdrawals)

In [6]:
total_d

np.int64(95500)

In [7]:
total_w

np.int64(-48000)

In [12]:
# Calculate net transaction amount.
net_amt = np.sum(transactions)
net_amt

np.int64(47500)

In [13]:
# Calculate absolute transaction values.
abs_t = np.abs(transactions)
abs_t

array([ 5000,  2000, 15000,  4500,  7000, 12000, 25000,  3000,  8000,
       18000,  4500, 22000,  6000,  9000,  2500])

In [15]:
# Find transactions whose absolute value is above the average absolute transaction.
avg_abs_t = np.mean(abs_t)
avg_abs_t

np.float64(9566.666666666666)

In [16]:
# Create labels "Credit" and "Debit".
labels = np.where(transactions > 0, "Credit", "Debit")
labels

array(['Credit', 'Debit', 'Credit', 'Debit', 'Credit', 'Debit', 'Credit',
       'Debit', 'Credit', 'Debit', 'Credit', 'Credit', 'Debit', 'Credit',
       'Debit'], dtype='<U6')

In [17]:
# Find percentage of transactions whose absolute value is greater than ₹10,000.
abs10k = abs_t[abs_t > 10000]
abs10k

array([15000, 12000, 25000, 18000, 22000])

In [18]:
m = len(abs10k)
n = len(abs_t)
perc = m*100/n
perc

33.333333333333336