<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_49.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
marks = [ 55,40,90,70,80]
bonus = 5
new_marks= []
for m in marks :
  new_marks.append(m+bonus)
print(new_marks)

[60, 45, 95, 75, 85]


#numpy


In [ ]:
#numpy stands for numerical

In [4]:
import numpy as np
bonus =10
marks = np.array([55,40,90,70,80])
new_marks = marks + bonus
print(new_marks)

[60, 45, 95, 75, 85]


In [7]:
#given a python list print every no twice
a =[3,6,1,9]
b = []
for i in a :
  b.append(i*2)
print(b)



[3, 5, 67, 9]


In [8]:
type(b)

list

In [12]:
a_np = np.array(a)
b_np = a_np * 2
print(b_np)

[ 6 12  2 18]


In [19]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [20]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
b = np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
b = np.arange(5)
print(b)
b

array([0, 1, 2, 3, 4])

In [42]:
b = np.arange(1,12)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])