<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_59.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
temperature = np.array([
  28.5, 31.2, 29.8, 35.6, 38.1,
  40.2, 27.9, 30.5, 42.3, 39.8,
  36.4, 33.2, 29.1, 41.7, 44.2,
  31.8, 34.5, 37.6, 26.9, 43.1
])

In [3]:
print(temperature)

[28.5 31.2 29.8 35.6 38.1 40.2 27.9 30.5 42.3 39.8 36.4 33.2 29.1 41.7
 44.2 31.8 34.5 37.6 26.9 43.1]


In [4]:
temperature.ndim

1

In [5]:
temperature.shape

(20,)

In [7]:
# Calculate mean, median, minimum and maximum.
avg_t= np.mean(temperature)
print(avg_t)

35.12


In [8]:
np.min(temperature)

np.float64(26.9)

In [9]:
np.max(temperature)

np.float64(44.2)

In [10]:
np.median(temperature)

np.float64(35.05)

In [11]:
np.std(temperature)

np.float64(5.410415880503088)

In [12]:
np.square(temperature)

array([ 812.25,  973.44,  888.04, 1267.36, 1451.61, 1616.04,  778.41,
        930.25, 1789.29, 1584.04, 1324.96, 1102.24,  846.81, 1738.89,
       1953.64, 1011.24, 1190.25, 1413.76,  723.61, 1857.61])

In [14]:
# Find all temperatures more than one standard deviation above the mean.
new_t = temperature[temperature>(np.mean(temperature)+np.std(temperature))]
print(new_t)

[42.3 41.7 44.2 43.1]


In [15]:
np.where(temperature>(np.mean(temperature)+np.std(temperature)),"yes","no")

array(['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'yes'],
      dtype='<U3')

In [16]:
# Calculate the absolute difference between every temperature and the mean.
np.abs(temperature-(np.mean(temperature)))

array([6.62, 3.92, 5.32, 0.48, 2.98, 5.08, 7.22, 4.62, 7.18, 4.68, 1.28,
       1.92, 6.02, 6.58, 9.08, 3.32, 0.62, 2.48, 8.22, 7.98])

In [24]:
# Find the five readings having the largest deviation from the mean.
largestd=np.sort(np.abs(temperature-(np.mean(temperature))))
print(largestd)


[0.48 0.62 1.28 1.92 2.48 2.98 3.32 3.92 4.62 4.68 5.08 5.32 6.02 6.58
 6.62 7.18 7.22 7.98 8.22 9.08]


In [23]:
largest5=largestd[-5:]
print(largest5)

[7.18 7.22 7.98 8.22 9.08]


In [25]:
# Round all temperatures to the nearest whole number.
np.round(temperature)

array([28., 31., 30., 36., 38., 40., 28., 30., 42., 40., 36., 33., 29.,
       42., 44., 32., 34., 38., 27., 43.])

In [26]:
cat_t = np.where(temperature >= 40, "Critical", np.where(temperature >= 35, "Warning", "Normal"))
print(cat_t)

['Normal' 'Normal' 'Normal' 'Warning' 'Warning' 'Critical' 'Normal'
 'Normal' 'Critical' 'Warning' 'Warning' 'Normal' 'Normal' 'Critical'
 'Critical' 'Normal' 'Normal' 'Warning' 'Normal' 'Critical']


In [27]:
critical_t = cat_t[ cat_t == "Critical"]
print(critical_t)

['Critical' 'Critical' 'Critical' 'Critical' 'Critical']


In [30]:
c=len(critical_t)
print(c)

5


In [32]:
# Reshape the readings into a 4 × 5 array.
reshapet=temperature.reshape(4,5)
print(reshapet)

[[28.5 31.2 29.8 35.6 38.1]
 [40.2 27.9 30.5 42.3 39.8]
 [36.4 33.2 29.1 41.7 44.2]
 [31.8 34.5 37.6 26.9 43.1]]


In [33]:
# Find the average temperature for each row.
np.mean(reshapet,axis=1)

array([32.64, 36.14, 36.92, 34.78])

In [34]:
employees = np.array([
  [101, 42000, 3, 450000],
  [102, 65000, 6, 720000],
  [103, 38000, 2, 300000],
  [104, 90000, 8, 950000],
  [105, 55000, 5, 610000],
  [106, 72000, 7, 830000]
])

In [35]:
# Extract salary, experience and annual sales.
salary = employees[:,1]
experience = employees[:,2]
sales = employees[:,3]


In [37]:
 #Calculate sales-to-salary ratio.
 sts= np.round(sales/salary)
 sts

array([11., 11.,  8., 11., 11., 12.])

In [38]:
# Find the employee with the highest annual sales.
employees[np.argmax(sales)]

array([   104,  90000,      8, 950000])

In [39]:
# Find employees having at least 5 years experience AND sales above ₹600,000.
criteria = (experience >= 5) & (sales > 600000)
employees[criteria]

array([[   102,  65000,      6, 720000],
       [   104,  90000,      8, 950000],
       [   105,  55000,      5, 610000],
       [   106,  72000,      7, 830000]])

In [40]:
bonus = np.where(sales>= 800000, 0.1*sales, np.where(sales >= 600000, 0.07*sales, 0.03*sales))
bonus

array([13500., 50400.,  9000., 95000., 42700., 83000.])

In [41]:
image = np.array([
  [10, 25, 40, 55, 70, 85],
  [20, 35, 50, 65, 80, 95],
  [30, 45, 60, 75, 90, 105],
  [40, 55, 70, 85, 100, 115],
  [50, 65, 80, 95, 110, 125],
  [60, 75, 90, 105, 120, 135]
])

In [45]:
# Extract the central 4 × 4 region.
center= image[1:5, 1:5]
print(center)

[[ 35  50  65  80]
 [ 45  60  75  90]
 [ 55  70  85 100]
 [ 65  80  95 110]]


In [47]:
 #Increase the central region by 20%.
image[1:5,1:5] = image[1:5,1:5]*1.2
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  50,  72,  93, 115,  95],
       [ 30,  64,  86, 108, 129, 105],
       [ 40,  79, 100, 122, 144, 115],
       [ 50,  93, 115, 136, 158, 125],
       [ 60,  75,  90, 105, 120, 135]])

In [48]:
# Cap all pixel values above 100 at 100.
image = np.where(image > 100, 100, image)
image

array([[ 10,  25,  40,  55,  70,  85],
       [ 20,  50,  72,  93, 100,  95],
       [ 30,  64,  86, 100, 100, 100],
       [ 40,  79, 100, 100, 100, 100],
       [ 50,  93, 100, 100, 100, 100],
       [ 60,  75,  90, 100, 100, 100]])

In [49]:
# Find pixels above the 75th percentile.
p75 = np.percentile(image, 75)
p75

np.float64(100.0)