<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture63%2664.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
prices = np.array([
    820, 835, 810, 850, 875,
    860, 890, 910, 895, 930,
    945, 920, 960, 975, 990
])

In [ ]:
Calculate percentage change between consecutive days.
Round percentage changes to 2 decimals.
Find days where price increased by more than 2%.
Find maximum, minimum and range.
Reshape prices into 3 × 5.
Find average price of each row.

In [3]:
diff = prices[1:] - prices[:-1]
diff

array([ 15, -25,  40,  25, -15,  30,  20, -15,  35,  15, -25,  40,  15,
        15])

In [4]:
# Calculate percentage change between consecutive days.
perc_change = np.round((diff*100)/prices[:-1],2)
perc_change


array([ 1.83, -2.99,  4.94,  2.94, -1.71,  3.49,  2.25, -1.65,  3.91,
        1.61, -2.65,  4.35,  1.56,  1.54])

In [5]:
# Find days where price increased by more than 2%.
high_change_days = np.where(perc_change > 2, "Yes", "No")
high_change_days

array(['No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No'], dtype='<U3')

In [6]:
# Find maximum, minimum and range.
mx = np.max(perc_change)
mn = np.min(perc_change)
range = mx-mn

In [7]:
# Reshape prices into 3 × 5.
new_price = prices.reshape(3,5)
new_price

array([[820, 835, 810, 850, 875],
       [860, 890, 910, 895, 930],
       [945, 920, 960, 975, 990]])

In [8]:
# Find average price of each row.
avg_row_price = np.mean(new_price, axis = 1)
avg_row_price

array([838., 897., 958.])

In [9]:
# A company records leads generated by four campaigns across five channels:
leads = np.array([
    [12000, 15000, 11000, 18000, 21000],
    [14000, 13000, 17000, 19000, 22000],
    [10000, 16000, 15000, 20000, 23000],
    [18000, 17000, 19000, 21000, 25000]
])

In [ ]:
Find total leads generated by each campaign.
Find total leads generated by each channel.
Find the campaign with maximum leads.
Find the channel with maximum leads.

In [10]:
# Find total leads generated by each campaign.
campaign_total = np.sum(leads, axis = 1)
campaign_total

array([ 77000,  85000,  84000, 100000])

In [11]:
# Find total leads generated by each channel.
channel_total = np.sum(leads, axis = 0)
channel_total

array([54000, 61000, 62000, 78000, 91000])

In [12]:
# Extract every second channel.
leads[:, 1::2]

array([[15000, 18000],
       [13000, 19000],
       [16000, 20000],
       [17000, 21000]])

#splitting array

In [13]:
numbers = np.array([
10, 20, 30, 40,
50, 60, 70, 80
])

In [16]:
n1=numbers[:4]
n1

array([10, 20, 30, 40])

In [17]:
n2 = numbers[4:]
n2

array([50, 60, 70, 80])

In [18]:
# np.split(array, no_of_splits)

In [19]:
parts = np.split(numbers, 2)
parts

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]

In [20]:
data = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
parts = np.split(data, 2, axis=0)
parts

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [21]:
data = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
parts = np.split(data, 2, axis=1)
parts

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [22]:
data = np.arange(1, 21).reshape(10, 2)
print(data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [23]:
train_data = data[:8]
test_data = data[-2:]

In [24]:
# Consider the following e-commerce dataset:
orders = np.array([
[101, 3, 1200, 4],
[102, 5, 800, 3],
[103, 2, 2500, 4],
[104, 8, 450, 4],
[105, 4, 1800, 3],
[106, 6, 950, 4],
[107, 3, 2200, 4],
[108, 10, 600, 3],
[109, 7, 1500, 4],
[110, 2, 3000, 4],
[111, 5, 750, 3],
[112, 9, 1250, 4]
])
# Order_ID
# Quantity
# Price
# Rating

In [25]:
# Extract every second order.
orders[1::2]

array([[ 102,    5,  800,    3],
       [ 104,    8,  450,    4],
       [ 106,    6,  950,    4],
       [ 108,   10,  600,    3],
       [ 110,    2, 3000,    4],
       [ 112,    9, 1250,    4]])

In [26]:
revenue = orders[:,1]*orders[:,2]
revenue

array([ 3600,  4000,  5000,  3600,  7200,  5700,  6600,  6000, 10500,
        6000,  3750, 11250])

In [29]:
quantity = orders[:,1]
price = orders[:,2]
rating = orders[:,3]

In [30]:
# Find orders where quantity >= 5 AND rating >= 3.
criteria = (quantity >= 5) & (rating >= 3)
criteria

array([False,  True, False,  True, False,  True, False,  True,  True,
       False,  True,  True])

In [34]:
# Find orders where quantity >= 5 AND rating >= 3.
criteria = (quantity >= 5) & (rating >= 3)
criteria

array([False,  True, False,  True, False,  True, False,  True,  True,
       False,  True,  True])

In [35]:
med_price = np.median(price)
med_price

np.float64(1225.0)

In [36]:
# Find orders where price is above median OR rating is below 4.
criteria = (price > med_price) | (rating < 4)
criteria

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True])

In [37]:
p25 = np.percentile(price,25)
p25

np.float64(787.5)

In [38]:
p75 = np.percentile(price,75)
p75

np.float64(1900.0)

In [39]:
# Find prices above the 75th percentile.
price75 = price[price > p75]
price75

array([2500, 2200, 3000])

In [40]:
# Find percentage of orders with rating >= 3.
ord3 = rating[rating >= 3]
perc = len(ord3)*100/len(rating)
perc

100.0

In [43]:
marks = np.random.randint(0,101,10)
marks


array([79, 86, 20, 10, 30, 90, 72, 23, 62, 62])

In [45]:
np.random.random()
#generates a random number between 0 to 1
# 0 <= value < 1

0.29233978499171154

In [46]:
# 3x4 --> random matrix.
np.random.random(12).reshape(3,4)

array([[0.16826697, 0.79685955, 0.48172131, 0.178623  ],
       [0.61915041, 0.68891942, 0.47978637, 0.12639413],
       [0.83562862, 0.99494981, 0.20918766, 0.70055556]])

In [47]:
#generate 20 random probability values and find their min, max, avg and perc greater than 0.5
probabilities = np.random.random(20)
max_prob = np.max(probabilities)
mn_prob = np.min(probabilities)
avg_prob = np.mean(probabilities)


In [48]:
np.random.rand(2)

array([0.99783868, 0.02425611])

In [49]:
num = np.random.rand(3,4)
num

array([[0.90808772, 0.32690401, 0.17147781, 0.56283204],
       [0.25752859, 0.96442133, 0.67700847, 0.89272064],
       [0.89204929, 0.27208157, 0.55796524, 0.11262846]])

In [50]:
# np.random.randint(start, stop)
#start --> inclusive, stop --> exclusive
num = np.random.randint(1,11)
num

3

In [51]:
a = np.random.uniform(20,30)
a

21.414592008853717

In [52]:
# 3x4 --> float
np.random.uniform(20,30,(3,4))


array([[29.42555897, 22.03164574, 21.51042107, 25.10723497],
       [21.52831615, 26.88749179, 27.83810117, 23.76927764],
       [28.609507  , 23.2494659 , 29.83736662, 27.75988749]])

In [53]:
np.random.seed(42)
n = np.random.randint(1,11,5)
print(n)

[7 4 8 5 7]


In [54]:
colors = np.array(["Red", "Blue", "Green", "White"])
colors

array(['Red', 'Blue', 'Green', 'White'], dtype='<U5')

In [55]:
lucky_draw = np.random.choice(colors,3)
lucky_draw

array(['Blue', 'Green', 'Green'], dtype='<U5')

In [56]:
lucky_draw = np.random.choice(colors,3, replace = False)
lucky_draw

array(['Red', 'Blue', 'White'], dtype='<U5')