<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_58.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np


In [ ]:
employees = np.array([
  [101, 35000, 1200000],
  [102, 48000, 400000],
  [103, 62000, 60000],
  [104, 40000, 130000],
  [105, 75000, 180000],
  [106, 55000, 50000]
])

In [ ]:
sales = employees[:,2]

In [ ]:
commission = np.where( sales > 200000 ,"exellent",np.where(sales>150000 , "good", " need improvement"))

In [ ]:
print(commission)

['exellent' 'exellent' ' need improvement' ' need improvement' 'good'
 ' need improvement']


In [ ]:
#employees with the sales >= 150000 recieve 5 % commission
icom = np.where( sales>= 150000, sales * 0.05,sales * 0.02)
print(icom)


[60000. 20000.  1200.  2600.  9000.  1000.]


In [ ]:
sales = np.array([
    120,150,180,200,220,250,270,300,320,350,380,400
])

In [ ]:
news=sales.reshape(4,3)
print(news)

[[120 150 180]
 [200 220 250]
 [270 300 320]
 [350 380 400]]


In [ ]:
np.sum(news,axis=1)

array([ 450,  670,  890, 1130])

In [ ]:
newsh= sales.reshape(-1,2)
print(newsh)

[[120 150]
 [180 200]
 [220 250]
 [270 300]
 [320 350]
 [380 400]]


In [ ]:
newsha=sales.reshape(2,-1)
print(newsha)

[[120 150 180 200 220 250]
 [270 300 320 350 380 400]]


In [ ]:
a = newsha.flatten()
print(a)

[120 150 180 200 220 250 270 300 320 350 380 400]


In [ ]:
np.mean(a)

np.float64(261.6666666666667)

In [ ]:
b= np.arange(30)

In [ ]:
c= b.reshape(2,5,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
b[0]

np.int64(0)

In [ ]:
c[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
c[0,1]

array([3, 4, 5])

In [ ]:
quantity = np.array([2,5,3,8,4,6,10,1,7,5,9,3])
price= np.array([
    120,150,180,200,220,250,270,300,320,350,380,400
])

In [ ]:
#calculate revenue for every product
rev= quantity*price
print(rev)

[ 240  750  540 1600  880 1500 2700  300 2240 1750 3420 1200]


In [ ]:
#calculate the total revenue
np.sum(rev)

np.int64(17120)

In [42]:
#find the index of highest revenue maker
np.argmax(rev)

np.int64(10)

In [ ]:
#extract the revenue of last 5 product
rev[-4:]

array([2240, 1750, 3420, 1200])

In [ ]:
avg_rev= np.mean(rev)

In [ ]:
np.where(rev>avg_rev,"yes","no")

array(['no', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'no'], dtype='<U3')