<a href="https://colab.research.google.com/github/rix7kz/AI-ML/blob/main/Lecture_56.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
marks = np.array([70,60,65,90,85])
print(np.mean(marks))

74.0


In [21]:
marks = np.array([70,60,65,90,85])
marks>70

array([False, False, False,  True,  True])

In [22]:
#write a code to filter out marks >70
a = [70,60,65,90,85]
b = []
for elem in a:
  if elem > 70:
    b.append(elem)

print(b)

[90, 85]


In [23]:
marks

array([70, 60, 65, 90, 85])

In [24]:
marks[[False, False, False,  True,  True]]

array([90, 85])

In [25]:
marks [ marks>70]

array([90, 85])

In [26]:
temperature  = np.array([
    24,28,31,35,29,22,37,30
])
#temperature ateleast 32

temperature [temperature >= 32]



array([35, 37])

In [27]:
prices = np.array([499,799,999,1199,1999])
prices [(prices>600)&(prices<999)]

array([799])

In [28]:
prices [(prices>600) & (prices<999)]

array([799])

In [29]:
prices[(prices<600) | (prices>999)]

array([ 499, 1199, 1999])

In [30]:
prices[~(prices>499)]

array([499])

In [31]:
marks = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


In [32]:
#find the value greater than 2 only in the first row
marks[0][marks[0]>2]

array([3, 4])

In [33]:
marks = np.array([
    [72,85,90,78],
    [65,70,75,80],
    [88,92,95,90],
    [55,60,58,65],
    [78,82,85,88]
])

In [34]:
#find shape and size of the array
marks.shape,marks.size

((5, 4), 20)

In [35]:
#marks obtained by the third student
marks[2]

array([88, 92, 95, 90])

In [36]:
#marks obtained in 2nd subject by all the students
marks [ : ,1]

array([85, 70, 92, 60, 82])

In [37]:
 #average marks of every student
 np.mean(marks,axis =1)

array([81.25, 72.5 , 91.25, 59.5 , 83.25])

In [38]:
#average marks in every subject
np.mean(marks,axis =0)

array([71.6, 77.8, 80.6, 80.2])

In [39]:
#student whos average is above 75
marks[ np.mean(marks,axis=1)>75]

array([[72, 85, 90, 78],
       [88, 92, 95, 90],
       [78, 82, 85, 88]])

In [40]:
#highest marks obtained in each subject
np.max(marks,axis=0)

array([88, 92, 95, 90])

In [42]:
#the complete row of the student with the highest average
ind = np.argmax(np.mean(marks,axis = 0))
marks[ind]

array([88, 92, 95, 90])

In [49]:
prices = np.array([
    499.50,799.90,1299.75,
    2499.50,3999.90,599.25,
    899.80,1599.40
])

In [50]:
#round prices to nearest whole number
np.round(prices)

array([ 500.,  800., 1300., 2500., 4000.,  599.,  900., 1599.])

In [51]:
#find product counting more than 1000
prices[prices > 1000]

array([1299.75, 2499.5 , 3999.9 , 1599.4 ])

In [65]:
#calculate a 15% discount only on price greater than 1000
discounted = np.round((prices[prices > 1000])*0.85)
print(discounted)

[1105. 2125. 3400. 1359.]


In [66]:
#calculate the average price of discountd price
np.round(np.mean(discounted))

np.float64(1997.0)

In [67]:
#find the most expensive original product
np.max(prices)

np.float64(3999.9)

In [68]:
np.argmax(prices)

np.int64(4)

In [69]:
#extract the last 4 product
prices[-4:]

array([3999.9 ,  599.25,  899.8 , 1599.4 ])

In [70]:
#calculate the square root of final product and round them to two decimal places
np.round(np.sqrt(discounted),2)

array([33.24, 46.1 , 58.31, 36.86])